### ISSUE TITLE
cpVal function: Possible typo

### ISSUE THREAD

**Issue by pablus** [christiankral/WindPowerPlants#15]
In the file WindPowerPlants/WindPowerPlants/Functions/cpVal.mo
There's a possible typo in the "Internal lambda" formulation.
According to Siegfried Heier, "Grid Integration of Wind Energy Conversion Systems", Second Edition,
 John Wiley, the "internal lambda" should be

lambda1 := 1 / (1 / (lambda + 0.08*beta) - 0.035 / (beta ^ 3 + 1));

and not

lambda1 := 1 / (1 / (lambda + 0.089) - 0.035 / (beta ^ 3 + 1));

I don't have access to the original book by Heier, cited in your paper 
"Open Source Library for the Simulation of Wind Power Plants"
where this possible typo is also encountered in equation (3),
so I should think it's probably a problem of Heier's English version.
Howerver, my teacher of wind power generation gave me the first formula
so I am a bit confused at this point. 
I kindly suggest you take a look at it, thank you.

**Comment by christiankral** [comment]
Thank you very much for your message. You are right, my equation in both the Modelica library and the paper "Open Source Library for the Simulation of Wind Power Plants" are wrong. 

I fixed the issue in the Modelica library and created the new version v0.9.7 in d36d549.

**Comment by christiankral** [comment]
For the sake of completeness:

Impact of the performed bug fix: All simulation results of the library are now deviating from previous simulation results.

**Comment by pablus** [comment]
Thank you so much for your attention. I will be using your library for my master thesis, it's great!. For the record, the following are two samples of the error introduced by the typo, calculated by gnu/octave. I don't think it's so bad :)

> > lambda = 5; beta = 5;
> > CpHeier(lambda, beta)_100
> > ans =  14.874
> > CpHeierTypo(lambda, beta)_100
> > ans =  12.793
> > lambda = 8; beta = 0;
> > CpHeier(lambda, beta)_100
> > ans =  41.092
> > CpHeierTypo(lambda, beta)_100
> > ans =  41.055

**Comment by tbeu** [comment]
Should it be 0.08*beta (as proposed by @pablus) or 0.089*beta (as in v0.9.7)?

**Comment by christiankral** [comment]
The equation for lambda1 is still not correct as  

  lambda1 := 1 / (1 / (lambda + 0.089*beta) - 0.035 / (beta ^ 3 + 1));

is used instead of 

  lambda1 := 1 / (1 / (lambda + 0.08*beta) - 0.035 / (beta ^ 3 + 1));

Fix is performed in 724ae6f.

**Comment by christiankral** [comment]
New release 0.9.8 is created.

**Comment by tbeu** [comment]
OK. Thanks. I just was wondering which coefficient is the right one ...

**Comment by christiankral** [comment]
The new equation of v0.9.8 may cause some numerical problems when simulating, e.g., WindPowerPlants.Examples.GenericPlantElectricRealData. Therefore, I added a numeric "offset" in the equation to achieve stable example simulations:

I thus changed 
  `lambda1 := 1 / (1 / (lambda + 0.08*beta) - 0.035 / (beta ^ 3 + 1));`
to
  `lambda1 := 1 / (1 / (lambda + 0.08*beta + Modelica.Constants.eps) - 0.035 / (beta ^ 3 + 1));`

This change which does not affect the overall energy and power harvest.
