### ISSUE TITLE
HTML conventions are not followed for h3

### ISSUE THREAD

**Issue by tbeu** [christiankral/WindPowerPlants#16]
Modelica (Standard Library) convention: `In the HTML documentation of any Modelica library, the headings <h1>, <h2> and <h3> should not be used, because they are utilized by the automatically generated documentation.`

See corresponding MSL ticket https://trac.modelica.org/Modelica/ticket/1746. Since WindPowerPlants depends on the MSL it might be useful to follow its conventions.

**Comment by christiankral** [comment]
Replaced tags `<h3>` by `<h4>` in  0f5e01a,
