### ISSUE TITLE
use of non-standard "NumberOfIntervals" annotation

### ISSUE THREAD

**Issue by dietmarw** [christiankral/WindPowerPlants#3]
You might consider replacing those annotations with the `interval` annotation instead.

**Comment by christiankral** [comment]
I thought, that I replaced all the "NumberOfIntervalls", but apparently this was not the case.

**Comment by christiankral** [comment]
Performed change in https://github.com/christiankral/WindPowerPlants/commit/e9a635e36a3cb3d77a4d57a073410d21ab730266
