### ISSUE TITLE
Numerically strange cp value

### ISSUE THREAD

**Issue by tbeu** [christiankral/WindPowerPlants#9]
The power coefficient WindPowerPlants.Examples.GenericPlantRealData.plant.windturbine.turbine.cp is either close to zero and one or is negative with very large magnitude of 10E+38 (Dymola) or even 10E+103 (SimulationX) at time instances. This leads to floating-point overflow in certain cases in SimulationX. Note that GenericPlantRayleigh is not affected. Only GenericPlantRealData and GenericPlantElectricRealData are affected.

**Comment by tbeu** [comment]
![cp](https://cloud.githubusercontent.com/assets/5444067/9194700/791ebf64-401d-11e5-8937-b6951f0c7de9.png)

**Comment by tbeu** [comment]
Can you reproduce it?

**Comment by christiankral** [comment]
I see there is a problem; I am working on a solution...

**Comment by tbeu** [comment]
OK, thanks for the feedback.

**Comment by christiankral** [comment]
I suppose the problem is solved in master. It took a couple investigations and changes in the library to make everything working. Please check whether the simulations now work fine with SimulationX.

**Comment by tbeu** [comment]
It still gives a floating-point overflow when computing cp.

``` c
turbineData_c1=0.50000000000000000;
turbineData_c2=116.00000000000000;
turbineData_c3=0.40000000000000002;
turbineData_c4=5.0000000000000000;
turbineData_c5=21.000000000000000;
turbineData_c6=0.00000000000000000;
beta=0.00000000000000000;
lambda=-0.10171009365613741;
lambda1=1/(1/(0.088999999999999996+lambda)- 0.035000000000000003/(1+beta*beta*beta)); /* -0.012704442043449671 */
cp=turbineData_c6*lambda1+turbineData_c1*(turbineData_c2/lambda1- (turbineData_c3*beta+turbineData_c4))*exp( -(turbineData_c5/lambda1));
```

The exponent `-(turbineData_c5/lambda1)` is about 1653 here which results in magnitude of 10E+717 for the natural power. Such a number cannot be represented by IEEE double precision floating-point arithmetic.

**Comment by tbeu** [comment]
Any news on this issue?

**Comment by christiankral** [comment]
I am sorry, but I have absolutely no time to work on this issue at the moment. However, I am very much interested in overcoming the problems. I somehow guess that I will have time by mid next week to work on this issue again.

**Comment by christiankral** [comment]
I restricted lambda to positive values which solves the issue on my opinion. This is also the correct physical solution since cp should not become negative at all. 

I checked in the solution in master. Please check and drop me a note.

**Comment by tbeu** [comment]
Cannot find the corresponding commit.

**Comment by christiankral** [comment]
Sorry, I did not commit properly. The changes should now be in.

**Comment by tbeu** [comment]
Should it better be this way?

``` mo
Real lambdaLimited(min=0) "Positive tip speed ratio";
/* ... */
lambdaLimited = if noEvent(lambda<0) then 0 else lambda;
```

**Comment by christiankral** [comment]
I incorporated your suggestion in master.

**Comment by tbeu** [comment]
Thanks. Can hopefully test it tomorrow.

**Comment by tbeu** [comment]
Fix confirmed.

@AlexMagdanz FYI.

**Comment by christiankral** [comment]
Created version v0.9.5 incorporating this fix.
